/**
 * Nine emotion families as DBT's Check the Facts and Opposite Action skills use
 * them, plus joy (added here: DBT gives joy no opposite action, so its card is
 * this project's own): what usually prompts each, the urge it brings, when it
 * fits the facts, what to do when it fits (problem-solve) and when it does not
 * (act opposite).
 *
 * Written for this project in its own words. `aliases` are the everyday words a
 * person uses for the feeling ("anxious" is fear, "hurt" is usually sadness), so
 * the tool can answer the word they actually said. `letThem` and `letMe` are the
 * Let Them / Let Me reading of each.
 */

export const EMOTIONS = [
  {
    id: "fear",
    name: "Fear",
    aliases: ["afraid", "scared", "anxious", "anxiety", "worried", "worry", "nervous", "panic", "panicky", "dread", "terrified", "uneasy", "on edge", "stressed", "overwhelmed", "insecure"],
    prompts: "A possible threat to your safety, health, livelihood or someone you love, or simply the unknown.",
    body: "Racing heart, shallow breathing, tight chest or stomach, restlessness, the urge to check things.",
    urge: "Run, freeze, hide, avoid, or keep checking for reassurance.",
    fitsWhen: "There is a real and reasonably likely danger to you or someone you care about.",
    ifItFits: "Problem-solve the danger: remove yourself or protect yourself, get information, make a plan, ask for help.",
    opposite: "Approach what you are avoiding, stay in the situation, and break it into small steps you repeat until the fear shrinks. Stop asking people to tell you it will be fine.",
    letThem: "Most fear about people is fear of what they will think of you or how they will react. Let them think it and react; you cannot head off every reaction. Not if the fear is of someone hurting, threatening or controlling you: that is never a let-them, and protecting yourself comes first.",
    letMe: "Let me check how likely the feared outcome really is, then take one small step towards the thing I am avoiding.",
    skills: ["check-the-facts", "opposite-action", "tipp", "cope-ahead", "mindfulness-of-current-emotion"],
  },
  {
    id: "anger",
    name: "Anger",
    aliases: ["angry", "mad", "furious", "irritated", "annoyed", "frustrated", "resentful", "rage", "livid", "pissed off", "fed up", "bitter", "outraged"],
    prompts: "A goal being blocked; you or someone you care about being hurt, insulted or treated unfairly; something you value being threatened.",
    body: "Heat in the face, clenched jaw or fists, muscles tensing, pressure to speak or act now.",
    urge: "Attack, shout, criticise, send the message, hit back.",
    fitsWhen: "An important goal was blocked, or you or someone you care about really was attacked, hurt, insulted or threatened.",
    ifItFits: "Problem-solve: address it directly with DEAR MAN, set a limit, escalate through the right channel, or protect yourself. Act on it skilfully, not explosively.",
    opposite: "Step gently away, stop replaying the grievance, loosen your body, and do something slightly kind or try to see their side.",
    letThem: "Let them be who they showed you they are. Fuming at the fact of it keeps you in the fight after they have moved on.",
    letMe: "Let me cool down before I act, then decide whether this is worth raising and, if so, raise it clearly once.",
    skills: ["stop", "tipp", "think", "check-the-facts", "dear-man", "opposite-action"],
  },
  {
    id: "sadness",
    name: "Sadness",
    aliases: ["sad", "down", "low", "hurt", "hurting", "gutted", "heartbroken", "lonely", "alone", "disappointed", "let down", "depressed", "empty", "grief", "grieving", "miserable", "rejected", "unwanted", "left out"],
    prompts: "Losing someone or something, things not turning out as you hoped, or being rejected.",
    body: "Heaviness, tiredness, a lump in the throat, tears, low energy.",
    urge: "Withdraw, go passive, stay in bed, isolate.",
    fitsWhen: "There has been a real loss, or a real gap between what you wanted and what is.",
    ifItFits: "Grieve it: let yourself feel it, get comfort from people, and when ready, plan how to rebuild or replace what was lost.",
    opposite: "Get moving, reach out to people, do something that brings pleasure or a sense of competence, and keep your attention in the present.",
    letThem: "Let them make the choices that hurt: leaving, not inviting, not calling. Their choice is real, and so is your sadness about it.",
    letMe: "Let me feel it without drowning in it: one act of care for my body, and one reach towards someone who reaches back.",
    skills: ["self-validation", "self-soothe", "opposite-action", "accumulate-positives", "radical-acceptance"],
  },
  {
    id: "shame",
    name: "Shame",
    aliases: ["ashamed", "embarrassed", "humiliated", "mortified", "worthless", "not good enough", "stupid", "exposed", "like a failure", "pathetic", "disgusted with myself"],
    prompts: "Something about you, or something you did, being exposed, and the risk that people who matter will reject you for it.",
    body: "Heat in the face, wanting to shrink, eyes down, a sinking feeling.",
    urge: "Hide, cover up, withdraw, avoid eye contact, or lash out to deflect attention.",
    fitsWhen: "A group that matters to you really would reject you if they knew, because of something that breaks its values.",
    ifItFits: "Repair where you can, keep it private from people who would reject you, or find a community whose values fit you better.",
    opposite: "Stop hiding: keep your head up and make eye contact, share it with people who will accept you, and keep doing the harmless thing openly.",
    letThem: "Let them think what they think about you. A verdict in someone else's head is not a measurement of your worth.",
    letMe: "Let me separate what I did from who I am, check whether anyone would really reject me, and speak to myself like a fair coach.",
    skills: ["check-the-facts", "self-validation", "opposite-action", "positive-self-talk", "nonjudgmental-stance"],
  },
  {
    id: "guilt",
    name: "Guilt",
    aliases: ["guilty", "regret", "remorse", "sorry", "bad about", "feel terrible", "it's my fault", "my fault", "selfish"],
    prompts: "Doing something, or failing to do something, that goes against your own values.",
    body: "Unease, a knot in the stomach, replaying what you did.",
    urge: "Apologise over and over, make up for it, hide, punish yourself.",
    fitsWhen: "You really did break your own moral code. Guilt over a reasonable boundary, or over someone else's disappointment, usually does not fit.",
    ifItFits: "Repair: apologise once and specifically, make amends, accept the consequences, and commit to doing it differently.",
    opposite: "When it does not fit: keep doing the harmless thing (saying no, resting, choosing yourself) without apologising, posture upright.",
    letThem: "Let them be disappointed in a fair decision. Their disappointment is not proof you did wrong.",
    letMe: "Let me ask whether I actually broke my own values. If I did, repair once. If I didn't, stop paying for it.",
    skills: ["check-the-facts", "problem-solving", "fast", "opposite-action", "self-validation"],
  },
  {
    id: "jealousy",
    name: "Jealousy",
    aliases: ["jealous", "possessive", "suspicious", "threatened", "insecure about them"],
    prompts: "Signs that a relationship, or something important to you, could be taken by someone else.",
    body: "Agitation, a tight chest, being on high alert, pictures that keep popping into your head.",
    urge: "Monitor, question, accuse, cling, control, check their phone.",
    fitsWhen: "A valued relationship or possession really is at risk of being lost to someone else.",
    ifItFits: "Raise it directly and calmly (DEAR MAN), ask for what you need, and decide what you will do if the risk is real.",
    opposite: "Stop checking and interrogating, loosen your grip, relax your hands and body, and let the other person have their freedom.",
    letThem: "Let them show you, through what they consistently do, how committed they are. Surveillance only tells you about your fear.",
    letMe: "Let me notice the urge to check without obeying it, and if there is a real concern, ask about it once, plainly.",
    skills: ["check-the-facts", "opposite-action", "dear-man", "mindfulness-of-current-emotion", "tipp"],
  },
  {
    id: "envy",
    name: "Envy",
    aliases: ["envious", "comparing", "comparison", "jealous of", "they have it all", "behind", "falling behind", "not as good as"],
    prompts: "Someone else having something you want and lack: a job, a partner, money, recognition, an easier start.",
    body: "A sour or hollow feeling, restlessness, the pull to keep scrolling.",
    urge: "Criticise, undermine or belittle them, or drive yourself hard out of comparison.",
    fitsWhen: "They really do have something you want and don't have.",
    ifItFits: "Use it as information: what does it tell you that you want? Study what is learnable in how they got it, and take one step towards your own version.",
    opposite: "Leave their thing alone, stop inflating their good fortune, list what you do have, and put the energy into your own goals.",
    letThem: "Let them have the promotion, the house, the audience. Some advantages cannot be copied, and their success does not shrink yours.",
    letMe: "Let me name the value the envy is pointing at and spend ten minutes on my own path today.",
    skills: ["what-skills", "check-the-facts", "build-mastery", "opposite-action", "abc-please"],
  },
  {
    id: "love",
    name: "Love",
    aliases: ["in love", "attached", "longing", "miss them", "missing them", "can't let go", "obsessed", "infatuated", "yearning"],
    prompts: "Someone or something that brings warmth or closeness, or meets your needs.",
    body: "Warmth, a pull towards the person, thinking about them often.",
    urge: "Get close, make contact, show affection, spend time together.",
    fitsWhen: "Loving them actually improves your life, or the lives of people you care about, and supports your goals.",
    ifItFits: "Express it, invest in the relationship, and enjoy it.",
    opposite: "When it does not fit (an ex who hurt you, someone unavailable): stop contact, stop expressing affection, remind yourself of the concrete reasons it doesn't work, and avoid reminders.",
    letThem: "Let them go if they have chosen to. Chasing someone who is leaving rarely changes who they are.",
    letMe: "Let me grieve what I hoped for, cut the reminders, and invest the longing in people who are here.",
    skills: ["radical-acceptance", "opposite-action", "turning-the-mind", "self-soothe", "build-mastery"],
  },
  {
    id: "disgust",
    name: "Disgust",
    aliases: ["disgusted", "repulsed", "grossed out", "contempt", "revolted", "sickened"],
    prompts: "Something that could contaminate or sicken you, or someone whose behaviour you find repellent or harmful.",
    body: "Nausea, a recoil, a curled lip, turning away.",
    urge: "Recoil, push away, avoid, sneer.",
    fitsWhen: "The thing could actually harm you, or the person's influence could damage you or your group.",
    ifItFits: "Protect yourself: keep your distance, set a limit, or leave the situation.",
    opposite: "When it does not fit: move closer when it is safe, stay present, be kind to the person and try to understand where they are coming from.",
    letThem: "Let them live by values that are not yours, where no one is being harmed.",
    letMe: "Let me check whether this is real harm or just difference, and keep my distance only where it protects me.",
    skills: ["check-the-facts", "nonjudgmental-stance", "think", "opposite-action"],
  },
  {
    id: "joy",
    name: "Joy",
    aliases: ["happy", "excited", "elated", "proud", "relieved", "grateful", "euphoric"],
    prompts: "Something going well: an achievement, connection, pleasure.",
    body: "Lightness, energy, smiling, wanting to move.",
    urge: "Share, celebrate, keep going, take on more.",
    fitsWhen: "Something good really happened and the energy matches its size.",
    ifItFits: "Savour it: notice it fully, share it, and let it count.",
    opposite: "Not a DBT opposite action (DBT doesn't give joy one), just sense: when elation is outsized or risky, slow your pace and voice, hold off on big decisions or spending, and check in with someone grounded.",
    letThem: "Let them react to your good news however they do. Their muted response is about them.",
    letMe: "Let me notice and keep the good moment, without needing anyone else to validate it.",
    skills: ["what-skills", "accumulate-positives", "how-skills"],
  },
];
