/**
 * Situation playbooks: the common hard moments, each cut along the Let Them / Let Me
 * line and pointed at the DBT skills that do the work.
 *
 * Every entry is written for this project in its own words. `skills` are ids in
 * skills.js (tests/content.test.mjs fails on a dangling one). `match` is the
 * keyword fallback for when the assistant does not name a situation itself: each
 * pattern that hits adds one to the score, and `requires` (when present) must ALSO
 * hit before the entry is a candidate at all, so "work" alone never picks
 * "criticism at work".
 *
 * `notLetThem` marks the situations where Let Them is the wrong tool: abuse,
 * harassment, a person at risk, a dependant's safety. The guide leads those with
 * safety and action, never with acceptance of the behaviour.
 */

export const SITUATIONS = [
  {
    id: "criticism-at-work",
    title: "Criticised at work",
    summary: "A manager, colleague or client criticises your work, maybe in front of others.",
    requires: [/\b(critici[sz]|critiqu|feedback|told me off|tore (it|me) apart|picked (it )?apart|called me out|reprimand|bad review|negative review|performance review|humiliat|embarrass)/],
    match: [/\b(boss|manager|work|job|colleague|co-?worker|meeting|team|client|review|presentation|report)\b/],
    letThem: "Let them hold their view of the work and deliver it in their own style.",
    letMe: "Let me pull the useful part away from the sting, ask clarifying questions, and decide what I will change and where I respectfully disagree.",
    skills: ["stop", "check-the-facts", "self-validation", "problem-solving", "dear-man"],
    firstStep: "Before replying, take one slow breath, then write each point of the criticism in neutral words and mark it accurate, partly accurate or not accurate.",
    caution: "If the criticism is repeated, personal or meant to humiliate (aimed at you, not the work), that may be bullying rather than feedback. That is not a let-them: keep a dated record and escalate.",
  },
  {
    id: "left-out",
    title: "Left out",
    summary: "Friends or family met up, or planned something, without you.",
    requires: [/\b(left out|excluded|not invited|wasn'?t invited|weren'?t invited|didn'?t invite|without me|no invite|uninvited|leave me out|left me out|cut(ting)? me out)\b/],
    match: [/\b(friends?|group|party|dinner|birthday|wedding|plans|photos?|stories|instagram|chat|sister|brother|cousin|family)\b/],
    letThem: "Let them choose their own guest list. They may have reasons you cannot see, and an invite list is not a verdict on your worth.",
    letMe: "Let me check what I actually know, let the hurt be there without spiralling, and decide whether to ask about it, invest in other friendships, or both.",
    skills: ["what-skills", "check-the-facts", "self-soothe", "dear-man", "build-mastery"],
    firstStep: "Write three explanations other than 'they don't like me', then decide whether to send one light, non-accusing message.",
  },
  {
    id: "waiting-for-a-reply",
    title: "They are not replying",
    summary: "A partner, date or friend has not answered, and your mind is filling the silence.",
    requires: [/\b(not (texting|replying|answering|responding)|hasn'?t (replied|texted|answered|responded)|haven'?t heard|no reply|no response|left (me )?on read|read receipts?|ignoring my (texts?|messages?|calls?)|won'?t (reply|answer|text))\b/],
    match: [/\b(partner|boyfriend|girlfriend|husband|wife|date|text|message|phone|whatsapp)\b/],
    letThem: "Let them reply on their own schedule. Their day, their phone habits and their focus are not mine to manage.",
    letMe: "Let me settle the alarm in my body, notice the story I am building, and if it is a real pattern, raise what I need at a calm time.",
    skills: ["tipp", "check-the-facts", "accepts", "dear-man", "cope-ahead"],
    firstStep: "Put the phone in another room for 30 minutes and do one absorbing task. Notice the urge to check without acting on it.",
  },
  {
    id: "family-judging-choices",
    title: "Family judging your choices",
    summary: "Parents or relatives disapprove of your career, partner, home, parenting or whether you have children.",
    requires: [
      /\b(mum|mom|mother|dad|father|parents?|family|in-?laws?|sister|brother|aunt|uncle|grand(ma|pa|mother|father)|relatives?)\b/,
      /\b(judg|disapprov|criticis|comment|opinion|nag|lectur|look down on|ashamed of me|disappointed in me)/,
    ],
    match: [/\b(choices?|career|parenting|decision|lifestyle|marry|married|kids|children|wedding|job|partner)\b/],
    letThem: "Let them keep opinions shaped by their own values, fears and generation.",
    letMe: "Let me live by my values, choose how much I share, and limit how often the topic gets airtime.",
    skills: ["wise-mind", "self-validation", "fast", "boundary-building", "give"],
    firstStep: "Prepare one calm line to repeat when it comes up, for example: 'I know this comes from caring. I've decided, and I'd like to talk about something else.'",
  },
  {
    id: "comparison",
    title: "Comparing yourself",
    summary: "Someone else's life, success, body or relationship makes yours feel small.",
    requires: [/\b(compar|envy|envious|jealous of (his|her|their|my)|everyone else|doing better than me|ahead of me|their life|so successful|instagram|social media|linkedin)/],
    match: [/\b(success|promotion|house|wedding|baby|body|followers|money|achiev|perfect)/],
    letThem: "Let them post their best moments and move at their own pace in life. Some of their advantages cannot be copied.",
    letMe: "Let me notice the envy, ask what value it is pointing at, and spend that energy on one step of my own.",
    skills: ["what-skills", "check-the-facts", "opposite-action", "build-mastery", "abc-please"],
    firstStep: "Close the app, name the feeling in one word, write the value it touched, and pick one 10-minute action towards that value.",
  },
  {
    id: "ex-moved-on",
    title: "An ex has moved on",
    summary: "A former partner is dating, happy, or telling the story their own way.",
    requires: [
      /\b(my ex|ex-?(partner|boyfriend|girlfriend|husband|wife)|former partner)\b/,
      /\b(moved on|new (partner|girlfriend|boyfriend)|dating|engaged|married|happy|breakup|break-up|broke up|seeing someone)\b/,
    ],
    match: [],
    letThem: "Let them date, be happy and tell the story of the breakup their own way.",
    letMe: "Let me grieve what ended, stop the checking, and rebuild my own days.",
    skills: ["radical-acceptance", "turning-the-mind", "opposite-action", "self-soothe", "build-mastery"],
    firstStep: "Mute or unfollow their accounts today, and put one plan in the diary this week that is just for you.",
  },
  {
    id: "someone-angry-at-me",
    title: "Someone is angry at you",
    summary: "A person is upset with you, shouting, sulking or blaming.",
    requires: [/\b(angry (at|with) me|mad at me|furious (at|with) me|upset with me|yell(s|ed|ing)? at me|scream(s|ed|ing)? at me|shout(s|ed|ing)? at me|blam(e|es|ed|ing) me|annoyed (at|with) me|giving me the silent treatment|silent treatment|blew up at me)\b/],
    match: [],
    letThem: "Let them be angry. The emotion is real for them, and calming it is their job.",
    letMe: "Let me stay steady, hear what is valid, own my share if I have one, and step away if it turns abusive.",
    skills: ["stop", "validation", "give", "check-the-facts", "fast"],
    firstStep: "Slow your voice and reflect back what you hear (for example, 'You're angry I missed the call') before defending yourself. If it keeps escalating, say you'll continue in an hour.",
    caution: "If they shout or rage at you often, you are afraid of how they will react, or you change what you do to avoid setting them off, that is not a let-them: put safety first and talk to a domestic abuse service (wise_mind_crisis_support).",
  },
  {
    id: "people-pleasing",
    title: "Saying yes when you mean no",
    summary: "You keep agreeing to things to avoid disappointing people.",
    requires: [/\b(people[- ]pleas|can'?t say no|cannot say no|always say yes|said yes when|hard to say no|say no|guilty (for|about) saying no|disappoint (them|people|her|him)|let (them|people) down|over-?commit)/],
    match: [/\b(favou?r|ask(ed|s)? me|request|volunteer|help|guilt)/],
    letThem: "Let them feel disappointed when I decline. Their disappointment is uncomfortable, not an emergency.",
    letMe: "Let me check my own capacity first and answer from wise mind rather than from fear.",
    skills: ["wise-mind", "pros-and-cons", "fast", "dear-man", "self-validation"],
    firstStep: "For the next request, say 'Let me check and come back to you' instead of yes, then decide within a day with a quick pros and cons list.",
  },
  {
    id: "setting-a-boundary",
    title: "Setting a boundary",
    summary: "You need to set or hold a limit with someone.",
    requires: [/\b(boundar|limit|keeps? (crossing|overstepping)|overstep|take advantage|taking advantage|walk(s|ing)? all over me|doormat)/],
    match: [],
    letThem: "Let them react however they react. Pushback, sulking or testing the line is their response, not proof the boundary is wrong.",
    letMe: "Let me define the limit, state it once clearly, and follow through with the consequence I control.",
    skills: ["boundary-building", "dear-man", "fast", "cope-ahead", "clarifying-priorities"],
    firstStep: "Write the boundary as 'If X happens, I will Y', where Y is something only you do, then say it aloud twice to rehearse.",
  },
  {
    id: "credit-taken",
    title: "Someone took credit for your work",
    summary: "A colleague presents your work, or your idea, as theirs.",
    requires: [/\b(took credit|takes credit|taking credit|stole my (idea|work)|steals my (idea|work)|my idea as (his|her|their)|claimed my work|claimed credit)\b/],
    match: [],
    letThem: "Let them present the work how they like in the meeting. I cannot control what comes out of their mouth.",
    letMe: "Let me make my contribution visible, keep a record, and raise it directly, or with my manager if it affects my review or pay. If it keeps happening, escalate.",
    skills: ["check-the-facts", "dear-man", "problem-solving", "clarifying-priorities", "fast"],
    firstStep: "Today, post a short factual recap of who did what in the project channel or send it to your manager, with no blame in it.",
  },
  {
    id: "parent-adult-child-conflict",
    title: "Conflict between a parent and an adult child",
    summary: "An ongoing clash between you and your adult child, or you and your parent.",
    requires: [
      /\b(my (adult )?(son|daughter|child|kid)|my (mum|mom|mother|dad|father|parents?))\b/,
      /\b(argu|fight|fought|conflict|won'?t speak|not speaking|estrang|disagree|clash|row|falling out|fell out|cut (me|us) off|blame)/,
      // Not a minor: a teenager, school matters or an age under 18 belong to teenager-risky-choices.
      /^(?!.*\bmy (son|daughter|child|kid)\b[^.]{0,40}\b(teen\w*|curfew|homework|grades|school|(1[0-7]|[1-9])[- ]?(yo|years?[- ]old))|.*\b(he|she|son|daughter|child|kid)('s| is) (1[0-7]|[1-9])\b(?! (years?|months?|weeks?|days?|hours?)\b(?![- ]old)))/,
    ],
    match: [/\b(adult|grown|always|years)\b/],
    letThem: "Let them make their own adult decisions and keep their own version of the past.",
    letMe: "Let me say what I feel and need once, clearly, and protect the relationship I want without needing to win the argument.",
    skills: ["validation", "think", "give", "dear-man", "walking-the-middle-path"],
    firstStep: "Before the next conversation, write one thing that is true from their side and one from yours, and open with theirs.",
  },
  {
    id: "ghosted",
    title: "Being ghosted",
    summary: "Someone stopped responding without explanation.",
    requires: [/\b(ghost(ed|ing)?|disappeared on me|vanished|stopped (talking|responding|replying) to me|blocked me)\b/],
    match: [],
    letThem: "Let them go quiet. The silence is an answer, even if it is an unkind way to give one.",
    letMe: "Let me close the loop myself rather than wait for them to close it.",
    skills: ["radical-acceptance", "turning-the-mind", "self-soothe", "opposite-action", "positive-self-talk"],
    firstStep: "Decide on one final message or none at all, then archive the chat and tell a friend you've stopped waiting.",
  },
  {
    id: "rumination",
    title: "Can't stop replaying it",
    summary: "Looping thoughts, replaying a conversation, often at night.",
    requires: [/\b(rumina|replay|can'?t stop thinking|keep thinking|overthink|spiral|in my head|can'?t sleep|lying awake|3 ?am|middle of the night|loop)/],
    match: [/\b(night|bed|sleep|thoughts?|mind)\b/],
    letThem: "Let them, whoever is in the loop, stay out of the bedroom. Nothing they do will change between now and morning.",
    letMe: "Let me move the problem onto paper and give my body the signal that it is time to rest.",
    skills: ["what-skills", "cope-ahead", "tipp", "accepts", "self-soothe", "abc-please"],
    firstStep: "Write the worry and one possible next step on paper, close the notebook, then breathe for 5 minutes with each out-breath longer than the in-breath.",
  },
  {
    id: "what-others-think",
    title: "Worrying what people think",
    summary: "Fear of judgement is shaping what you do.",
    requires: [/\b(what (people|others|they|everyone) (think|will think|might think)|judg(e|ed|ing|ment)|look stupid|embarrass|approval|opinion of me|think less of me|laugh at me)/],
    match: [/\b(anxious|anxiety|worried|nervous|scared|afraid|post|speak up|share)\b/],
    letThem: "Let them form impressions. I cannot steer what goes on in someone else's head.",
    letMe: "Let me act on my values, test my predictions, and treat the fear as a feeling rather than a fact.",
    skills: ["check-the-facts", "opposite-action", "positive-self-talk", "self-validation", "nonjudgmental-stance"],
    firstStep: "Write the exact judgement you fear and rate how likely it is from 0 to 100, then do a small version of the feared thing and note what actually happened.",
  },
  {
    id: "procrastination",
    title: "Putting it off",
    summary: "Avoiding a task, often because of how others will judge it.",
    requires: [/\b(procrastinat|putting (it )?off|keep avoiding|can'?t (get )?start|can'?t make myself|stuck on|deadline|unmotivated|no motivation)/],
    match: [],
    letThem: "Let them (the boss, the deadline, the people waiting) hold their expectations. Picturing their reaction is not moving the task.",
    letMe: "Let me start smaller than feels worthwhile and bring the reluctance along with me.",
    skills: ["willingness", "opposite-action", "build-mastery", "problem-solving", "positive-self-talk"],
    firstStep: "Set a 10-minute timer and do only the first visible step, such as opening the file and typing the heading.",
  },
  {
    id: "they-wont-change",
    title: "They won't change",
    summary: "The same pattern keeps repeating: cancelling, mess, lateness, broken promises.",
    requires: [/\b(won'?t change|never changes?|keeps? (doing|cancel|forgett|leaving|being late|breaking)|again and again|same (thing|pattern) (again|every)|every (single )?time|always (late|cancels?|forgets?)|broken promises?)/],
    match: [],
    letThem: "Let them keep the pattern, and assume it will continue unless something shifts.",
    letMe: "Let me decide what I will do given the pattern: ask clearly once, adjust my expectations, change how much I invest, or step back.",
    skills: ["radical-acceptance", "pros-and-cons", "dear-man", "clarifying-priorities", "wise-mind"],
    firstStep: "Write the pattern as a plain fact, list your three realistic options, and pick one to try for two weeks.",
  },
  {
    id: "grief-and-loss",
    title: "Grief and loss",
    summary: "A death, a loss, or an ending you did not choose.",
    requires: [/\b(died|passed away|death|funeral|grief|griev|bereave|loss of|lost my|miscarr|terminal)/],
    match: [/\b(miss (him|her|them)|struggling|anniversary|since (he|she|they) (died|passed)|grief|grieving)\b/],
    letThem: "Let it be what it was: the loss happened. Let others grieve, or fail to support you well, in their own clumsy ways.",
    letMe: "Let me feel the grief as it comes in waves, look after my body, and accept help.",
    skills: ["radical-acceptance", "self-validation", "self-soothe", "abc-please", "willingness"],
    firstStep: "Do one basic care task today (a meal, a shower or a short walk) and tell one person honestly how you are.",
  },
  {
    id: "someone-elses-drinking",
    title: "Someone's drinking or drug use",
    summary: "A partner, friend or adult relative is drinking too much or using.",
    requires: [/\b(drink(s|ing)? too much|drunk|alcohol|drinking problem|addict|addiction|using (drugs|again)|high again|relapse)/],
    match: [/\b(partner|husband|wife|boyfriend|girlfriend|dad|mum|mom|brother|sister|friend|son|daughter)\b/],
    letThem: "Let them own their choices about using, as an adult. I cannot make another adult change.",
    letMe: "Let me protect my safety and money, say what I see once with care, and get support for myself. If there is danger (driving, violence, children present), I act.",
    skills: ["dear-man", "boundary-building", "validation", "radical-acceptance", "problem-solving"],
    firstStep: "Pick one limit you will keep, for example not getting in the car after they have been drinking, and tell them at a sober, calm moment.",
    caution: "If anyone is in danger (drink-driving, violence, children unsupervised), this is not a let-them situation: act on safety first. If the person using is a child or teenager in your care, it is not a let-them either: their safety is yours to protect.",
  },
  {
    id: "lending-money",
    title: "Asked for money again",
    summary: "A sibling, friend or relative keeps asking to borrow money.",
    requires: [/\b(borrow|lend|loan|owe[sd]? me|asking for money|asks? me for money|bail (them|him|her) out|pa(y|id) (me )?back)\b/],
    match: [/\b(money|cash|rent|debt|again)\b/],
    letThem: "Let them manage their own finances, and let them feel frustrated when I say no.",
    letMe: "Let me decide what I can afford to give (not lend), and say it plainly.",
    skills: ["wise-mind", "pros-and-cons", "fast", "dear-man", "boundary-building"],
    firstStep: "Decide your amount, which may be zero, before the next request, and write the one-line answer you'll give.",
  },
  {
    id: "disagree-with-decision",
    title: "A decision you disagree with",
    summary: "Your manager, or someone with authority, made a call you think is wrong.",
    requires: [
      /\b(disagree|wrong (decision|call)|bad (decision|call)|overruled|their decision|his decision|her decision|decided without)\b/,
      /\b(boss|manager|director|lead|company|management|work|team)\b/,
    ],
    match: [],
    letThem: "Let them make the call. It falls within their role.",
    letMe: "Let me give my input once, clearly and with reasons, then decide whether to commit, keep raising it through proper channels, or start planning a move.",
    skills: ["dear-man", "wise-mind", "radical-acceptance", "walking-the-middle-path", "pros-and-cons"],
    firstStep: "Write your concern in three sentences (what you see, the risk, what you propose) and ask for 10 minutes to discuss it.",
    caution: "If the decision creates a safety risk, breaks the law or policy, or is discriminatory, it is not a let-them: put the concern in writing and escalate through a manager, HR, a union or a whistleblowing channel.",
  },
  {
    id: "passed-over",
    title: "Passed over",
    summary: "You did not get the promotion, the role or the opportunity.",
    requires: [/\b(passed over|didn'?t get the (job|promotion|role)|got the promotion|gave (it|the role|the job) to|rejected|not selected|turned down for)\b/],
    match: [/\b(promotion|job|role|interview|raise|position)\b/],
    letThem: "Let them make the decision, even if I think it was wrong.",
    letMe: "Let me ask for specific feedback and choose a plan: grow towards it here, or look elsewhere.",
    skills: ["radical-acceptance", "self-validation", "dear-man", "problem-solving", "build-mastery"],
    firstStep: "Ask the decision-maker for 20 minutes to understand what would have made the difference, and go in to listen, not to appeal.",
    caution: "If you think the decision was discrimination (pregnancy, sex, race, age, disability, religion and so on), it is not a let-them: write down what happened and get HR, union or legal advice.",
  },
  {
    id: "teenager-risky-choices",
    title: "A teenager taking risks",
    summary: "A child or teenager in your care is making risky choices.",
    requires: [/\b(teens?|teenage[rd]?|teenagers|adolescents?|(1[0-7]|[1-9])[- ]?(yo|years?[- ]old)|my (son|daughter|kid|child)|stepson|stepdaughter|grandchild)\b/],
    match: [/\b(risk|danger|vap|drink|drunk|alcohol|drugs|weed|sneak|lying|curfew|grades|skipping|unsafe|older (boy|girl|guy|man))/],
    letThem: "Let them have their own feelings, tastes and some low-risk mistakes; that is how they learn. Never 'let them' when their safety is at stake.",
    letMe: "Let me stay responsible for safety, set clear house rules, and validate their feelings while holding the limit.",
    skills: ["validation", "walking-the-middle-path", "think", "dear-man", "boundary-building"],
    firstStep: "Sort the issue into three: safety (you act), values (you discuss), personal preference (you let go). Deal with the safety items first.",
    notLetThem: "A dependant's safety is yours to protect. Accept their feelings and low-risk choices, but dangerous choices need limits, supervision and action.",
  },
  {
    id: "shared-problem",
    title: "A shared problem nobody is fixing",
    summary: "A housemate, partner or co-parent is not pulling their weight on something you share.",
    requires: [/\b(housemate|flatmate|roommate|co-?parent\w*|chores|household|not pulling (their|his|her) weight|do(es)? nothing (around|at) (the )?house|split the|my share|fair share|rent|bills|joint (account|money|savings|mortgage)|our (money|savings|mortgage|account|house|flat|home|bills)|mortgage|child support|custody|(their|his|her|my) half(?![- ]?(brother|sister|sibling)s?\b))\b/],
    match: [],
    letThem: "Let them have different standards. I won't make them care about this the way I do.",
    letMe: "Let me propose a concrete system and negotiate, because the outcome lands on both of us.",
    skills: ["problem-solving", "dear-man", "give", "walking-the-middle-path"],
    firstStep: "Ask for a 15-minute chat and bring one specific proposal, such as a rota or a split of tasks, rather than a list of complaints.",
  },
  {
    id: "harassment-at-work",
    title: "Harassment or discrimination",
    summary: "Harassment, bullying or discrimination at work or school.",
    requires: [/\b(harass|discriminat|bully|bullied|bullying|racis|sexis|homophob|transphob|hostile work|slurs?\b|sexual (comments?|jokes?|remarks?|innuendo|advances?|messages?|photos?|pictures?)|inappropriate(ly)? (comments?|jokes?|remarks?|messages?|touch\w*)|unwanted (advances?|touch\w*|messages?|photos?|pictures?|attention)|grop(e|es|ed|ing)|(keeps?|kept) touching me|touch(es|ed|ing)? me inappropriately|hitting on me|(comments?|remarks?) about my (body|looks|appearance|race|religion|accent|skin|chest|breasts|bum)|(boss|manager|supervisor|colleagues?|co-?workers?|teachers?|lecturer|coach|clients?|customers?)\b[^.]{0,60}\b(comment\w*|remarks?|jokes?)\b[^.]{0,30}\b(weight|body|figure|looks|appearance))/],
    match: [],
    letThem: "Do not let them. Accept that it happened, so you stop doubting yourself, but never accept it as okay.",
    letMe: "Let me document what happened, get support, and escalate through HR, a union, a trusted manager or legal advice.",
    skills: ["radical-acceptance", "check-the-facts", "clarifying-priorities", "dear-man", "fast"],
    firstStep: "Write a dated, factual note of what happened, where, and who was present, and keep it somewhere private that you control.",
    notLetThem: "Harassment and discrimination are never a let-them situation. Acceptance here means believing your own account so you can act on it.",
  },
  {
    id: "controlling-partner",
    title: "A partner who controls, threatens or demeans",
    summary: "Control, threats, intimidation, monitoring, or being put down by a partner or family member.",
    requires: [/\b((he|she|they|partner|husband|wife|boyfriend|girlfriend|spouse|ex|mum|mom|mother|dad|father|step(mum|mom|dad|mother|father)|brother|sister|son|daughter|parents?|uncle|aunt|grand\w+|gran(ny)?) (hits?|hit|hurts?|pushed|shoved) me\b|threaten(s|ed|ing)? (me|to (hurt|kill|take|leave me))|controls (my|me)|checks my phone|won'?t let me (leave|see|go|have)|(afraid|scared|frightened|terrified) of (him|her|them|my partner)|(afraid|scared|frightened|terrified) of (his|her|their|my partner'?s) (temper|anger|rage|reactions?|moods?)|abus(e|es|ed|ive)\b|abusing (me|us|the (kids|children)|my (kids|children|son|daughter))\b|coercive|stalk|isolat(es|ing) me|(partner|husband|wife|boyfriend|girlfriend|spouse|ex|he|she)\b[^.]{0,40}\b(controll?ing|put(s)? me down|demean|belittl))/],
    match: [],
    letThem: "This is not a let-them situation. Accept the reality of what is happening so you can act on it, never so you can put up with it.",
    letMe: "Let me put safety first, tell someone I trust, and make a plan with expert help.",
    skills: ["radical-acceptance", "wise-mind", "problem-solving", "cope-ahead"],
    firstStep: "Contact a domestic abuse helpline or tell one trusted person today. If you are in immediate danger, call emergency services.",
    notLetThem: "Never 'let them' hurt, threaten, coerce or control you. A domestic abuse service can help you plan safely, including how to leave safely.",
    safety: true,
  },
  {
    id: "friend-at-risk",
    title: "Someone you know may be at risk",
    summary: "A friend or family member has talked about suicide or self-harm.",
    requires: [/\b(friend|partner|sister|brother|son|daughter|mum|mom|dad|someone|colleague|he|she|they)\b[^.]{0,60}\b(suicid|kill (him|her|them)sel(f|ves)|end (his|her|their) life|self-?harm|cutting(?! (me|us|you|corners|ties|back|down|off|out|costs?|class|classes|school|lessons)\b| in (line|on)\b| it (close|fine)\b| the (grass|lawn|hedge|cake|bread|cord|line)\b)|want(s)? to die|overdose)/],
    match: [],
    letThem: "Don't step back here. I cannot control their choices, but I don't leave them alone with it.",
    letMe: "Let me take it seriously, stay with them, and connect them to crisis help.",
    skills: ["stop", "validation", "give", "problem-solving"],
    firstStep: "Ask them directly whether they are thinking of ending their life. If yes, contact a crisis line or emergency services together.",
    notLetThem: "When someone may be at risk of suicide or self-harm, Let Them does not apply: stay close and get crisis help involved.",
    safety: true,
  },
  {
    id: "holiday-family-pressure",
    title: "Family pressure over plans",
    summary: "In-laws or relatives pushing for holidays, visits or traditions.",
    requires: [/\b(christmas|holiday|holidays|thanksgiving|easter|eid|diwali|hanukkah|new year|visit|visiting|family (dinner|gathering|event))\b/],
    match: [/\b(in-?laws?|family|parents|expect|pressure|guilt|insist|offended)/],
    letThem: "Let them want us there and feel let down if we don't come.",
    letMe: "Let me agree a position with my partner first, then offer what we can genuinely give, kindly and without over-apologising.",
    skills: ["wise-mind", "walking-the-middle-path", "dear-man", "give", "fast"],
    firstStep: "Agree a joint answer with your partner before either of you replies to anyone.",
  },
  {
    id: "rude-stranger",
    title: "A rude stranger",
    summary: "Someone rude online, in traffic, in a shop or on a call.",
    requires: [/\b(stranger|rude|cut me off|road rage|traffic|online|comment section|troll|reddit|twitter|customer service|cashier|driver)\b/],
    match: [/\b(rude|angry|furious|yell|scream|shout|swore|swearing|insult|honk|gesture)/],
    letThem: "Let them be rude. I will never see them again, and their mood belongs to them.",
    letMe: "Let me let the adrenaline settle and choose not to feed the exchange.",
    skills: ["stop", "tipp", "opposite-action", "nonjudgmental-stance"],
    firstStep: "Unclench your hands and jaw, take three slow breaths, and don't reply or gesture back.",
  },
  {
    id: "friendship-drifting",
    title: "A friendship drifting away",
    summary: "A friend has less time or interest than before.",
    requires: [/\b(drift|drifting|grown apart|growing apart|don'?t talk (anymore|as much)|never (calls|texts|reaches out)|always me (who|reaching)|one-sided|lost touch|best friend)\b/],
    match: [/\b(friend|friendship)\b/],
    letThem: "Let them have less time or interest than before. Friendships change shape over the years, often through proximity, timing and energy rather than rejection.",
    letMe: "Let me reach out once in a way that is easy to say yes to, then put more of my energy where it is returned.",
    skills: ["radical-acceptance", "dear-man", "build-mastery", "self-soothe"],
    firstStep: "Send one low-pressure invitation with a specific time and place, and decide in advance that a no or no reply is information, not an insult.",
  },
  {
    id: "partner-wont-commit",
    title: "A partner who won't commit",
    summary: "Mixed signals, someone keeping you at a distance, or unclear where it is going.",
    requires: [/\b(won'?t commit|commitment|mixed signals|situationship|hot and cold|not sure (he|she|they) (likes?|wants?) me|keeps? me (at a distance|hanging)|where (this|it) is going|define the relationship)\b/],
    match: [],
    letThem: "Let them show me, over time, how invested they really are. Their consistent behaviour is the answer.",
    letMe: "Let me ask directly what they want, decide what I need, and leave if those don't match.",
    skills: ["check-the-facts", "wise-mind", "dear-man", "fast", "radical-acceptance"],
    firstStep: "Write down what they have consistently done (not said) over the last month, then decide the one question you will ask them directly.",
  },
  {
    id: "adult-meltdown",
    title: "An adult melting down",
    summary: "A grown-up is sulking, stonewalling or exploding, and you feel responsible for fixing it.",
    requires: [/\b(meltdown|tantrum|sulk|stonewall|explod|lost (his|her|their) temper|freak(ed|ing)? out|walk(ing)? on eggshells|keep the peace|manage (his|her|their) (mood|feelings|emotions))/],
    match: [],
    letThem: "Let them have the reaction. Regulating their emotions is their job, not mine.",
    letMe: "Let me stay calm, not argue inside the wave, and keep my boundaries. If it turns frightening or abusive, I leave and get support.",
    skills: ["stop", "validation", "give", "fast", "boundary-building"],
    firstStep: "Say one validating sentence ('I can see you're really upset'), then wait. Don't explain or defend until the surge has passed.",
    caution: "If they explode often, you are afraid of how they will react, or you change what you do to avoid setting them off, that pattern can be a sign of an abusive or controlling relationship. That is not a let-them: put safety first and talk to a domestic abuse service (wise_mind_crisis_support).",
  },
  {
    id: "comments-about-body",
    title: "Comments about your body or looks",
    summary: "Someone keeps remarking on your weight, eating, body or appearance.",
    requires: [
      /\b(comments?|commenting|remarks?|says?|said|keeps? (saying|telling|asking)|mentions?|jokes?|teas(e|es|ing)|puts? me down|critici[sz]\w*)\b/,
      // Not at work: a boss's or colleague's comments about a body are harassment-at-work.
      /^(?!.*\b(sexual\w*|boss|manager|supervisor|colleagues?|co-?workers?|at work|clients?|customers?|teachers?|lecturer|coach)\b).*\b(weight|fat|thin|skinny|body|appearance|figure|diet|portions?|my (looks|food|eating|skin|hair|clothes|plate)|(what|how much) i eat)\b/,
    ],
    match: [/\b(mum|mom|mother|dad|father|parents?|family|aunt|grand\w*|partner|friend|every time|always)\b/],
    letThem: "Let them have opinions about bodies, shaped by their own history and worries. Their comment is about their lens, not a measurement of you.",
    letMe: "Let me decide what I will discuss, say once that the topic is off the table, and change the subject or leave the room when it comes up.",
    skills: ["boundary-building", "fast", "self-validation", "dear-man", "nonjudgmental-stance"],
    firstStep: "Choose one calm line and use it every time: 'I'm not discussing my body. How's the garden?' Then change the subject, without explaining.",
    caution: "If comments like these are feeding into worries about eating, food or how your body looks, that deserves support of its own: a GP or an eating disorder service can help.",
  },
];

/** Every id, for schema enums and the content tests. */
export const SITUATION_IDS = SITUATIONS.map((s) => s.id);
