/**
 * Writes src/icon.js: the icon as SVG text, and the same drawing as a 180x180 PNG.
 *
 * The mark is DBT's own diagram: reasonable mind and emotion mind as two circles,
 * and wise mind as the place they overlap. The PNG exists because not every MCP
 * client renders an SVG icon; it is rasterised here, in plain Node with no image
 * library, from the same geometry as the SVG, so the two cannot drift apart.
 *
 *   node scripts/build-icon.mjs
 */

import { writeFileSync } from "node:fs";
import { deflateSync } from "node:zlib";

const BG = [16, 25, 43];
const LEFT = { cx: 25, cy: 32, r: 15, rgb: [111, 168, 255], alpha: 0.55 };
const RIGHT = { cx: 39, cy: 32, r: 15, rgb: [255, 143, 122], alpha: 0.55 };
const LENS = [245, 211, 122];
const RADIUS = 14;

const h = Math.sqrt(LEFT.r ** 2 - ((RIGHT.cx - LEFT.cx) / 2) ** 2);
const top = (32 - h).toFixed(3);
const bottom = (32 + h).toFixed(3);
const hex = (rgb) => `#${rgb.map((v) => v.toString(16).padStart(2, "0")).join("").toUpperCase()}`;

const SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">` +
  `<title>Wise Mind</title>` +
  `<rect width="64" height="64" rx="${RADIUS}" fill="${hex(BG)}"/>` +
  `<circle cx="${LEFT.cx}" cy="${LEFT.cy}" r="${LEFT.r}" fill="${hex(LEFT.rgb)}" fill-opacity="${LEFT.alpha}"/>` +
  `<circle cx="${RIGHT.cx}" cy="${RIGHT.cy}" r="${RIGHT.r}" fill="${hex(RIGHT.rgb)}" fill-opacity="${RIGHT.alpha}"/>` +
  `<path d="M32 ${top}A${LEFT.r} ${LEFT.r} 0 0 1 32 ${bottom}A${RIGHT.r} ${RIGHT.r} 0 0 1 32 ${top}Z" fill="${hex(LENS)}"/>` +
  `</svg>`;

/** The colour of one point in the 64x64 drawing, or null outside the rounded square. */
function paint(x, y) {
  const cx = Math.min(Math.max(x, RADIUS), 64 - RADIUS);
  const cy = Math.min(Math.max(y, RADIUS), 64 - RADIUS);
  if ((x - cx) ** 2 + (y - cy) ** 2 > RADIUS ** 2) return null;
  const inL = (x - LEFT.cx) ** 2 + (y - LEFT.cy) ** 2 <= LEFT.r ** 2;
  const inR = (x - RIGHT.cx) ** 2 + (y - RIGHT.cy) ** 2 <= RIGHT.r ** 2;
  if (inL && inR) return LENS;
  let rgb = BG;
  for (const [inside, c] of [[inL, LEFT], [inR, RIGHT]]) {
    if (inside) rgb = rgb.map((v, i) => v * (1 - c.alpha) + c.rgb[i] * c.alpha);
  }
  return rgb;
}

function png(size, samples = 4) {
  const rows = [];
  for (let py = 0; py < size; py++) {
    const row = [0];
    for (let px = 0; px < size; px++) {
      let r = 0, g = 0, b = 0, a = 0;
      for (let sy = 0; sy < samples; sy++) {
        for (let sx = 0; sx < samples; sx++) {
          const c = paint(((px + (sx + 0.5) / samples) * 64) / size, ((py + (sy + 0.5) / samples) * 64) / size);
          if (!c) continue;
          r += c[0]; g += c[1]; b += c[2]; a++;
        }
      }
      const n = samples * samples;
      row.push(a ? Math.round(r / a) : 0, a ? Math.round(g / a) : 0, a ? Math.round(b / a) : 0, Math.round((255 * a) / n));
    }
    rows.push(Buffer.from(row));
  }
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc = (buf) => {
    let c = 0xffffffff;
    for (const byte of buf) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
    const sum = Buffer.alloc(4);
    sum.writeUInt32BE(crc(body));
    return Buffer.concat([len, body, sum]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr.set([8, 6, 0, 0, 0], 8);
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(Buffer.concat(rows), { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

const out = [
  "// Generated by scripts/build-icon.mjs. Edit the script, not this file.",
  `export const ICON_SVG = ${JSON.stringify(SVG)};`,
  `export const ICON_PNG_BASE64 = ${JSON.stringify(png(180).toString("base64"))};`,
  "",
].join("\n");
writeFileSync(new URL("../src/icon.js", import.meta.url), out);
console.log(`src/icon.js: svg ${SVG.length} bytes, png ${png(180).length} bytes`);
